Name:           perl-Email-Date
Version:        1.104
Release:        1%{?dist}
Summary:        Find and Format Date Headers
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Email-Date/
Source0:        http://www.cpan.org/authors/id/R/RJ/RJBS/Email-Date-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Capture::Tiny)
BuildRequires:  perl(Date::Parse) >= 2.27
BuildRequires:  perl(Email::Abstract) >= 2.10
BuildRequires:  perl(Email::Date::Format) >= 1.000
BuildRequires:  perl(Exporter) >= 5.57
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More) >= 0.96
BuildRequires:  perl(Time::Piece) >= 1.08
Requires:       perl(Date::Parse) >= 2.27
Requires:       perl(Email::Abstract) >= 2.10
Requires:       perl(Email::Date::Format) >= 1.000
Requires:       perl(Exporter) >= 5.57
Requires:       perl(Time::Piece) >= 1.08
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Achtung! Probably you'll be find just using Email::Date::Format to produce
dates or Date::Parse to parse dates. This module isn't much needed anymore,
but does provide find_date, described below.

%prep
%setup -q -n Email-Date-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Sep 30 2015 SWAELENS Jonathan <jonathan@opensides.be> 1.104-1
- Specfile autogenerated by cpanspec 1.78.
