Name:           perl-App-Daemon
Version:        0.22
Release:        1%{?dist}
Summary:        Start an Application as a Daemon
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/App-Daemon/
Source0:        http://www.cpan.org/authors/id/M/MS/MSCHILLI/App-Daemon-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Pid)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(Log::Log4perl) >= 1.0
BuildRequires:  perl(Pod::Usage)
BuildRequires:  perl(Sysadm::Install) >= 0.37
BuildRequires:  perl(Test::More)
Requires:       perl(File::Pid)
Requires:       perl(File::Temp)
Requires:       perl(Log::Log4perl) >= 1.0
Requires:       perl(Pod::Usage)
Requires:       perl(Sysadm::Install) >= 0.37
Requires:       perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
App::Daemon helps running an application as a daemon. The idea is that you
prepend your script with the

%prep
%setup -q -n App-Daemon-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Sep 30 2015 SWAELENS Jonathan <jonathan@opensides.be> 0.22-1
- Specfile autogenerated by cpanspec 1.78.
